mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: nndata-aws-admin@nndata.com
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: aws-logs@nndata.com
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: aws-audit@nndata.com
    organizationalUnit: Security
    warm: false
workloadAccounts:
  - name: LogArchiveGC # referred to as LogArchive in the GovCloud account-config.yaml
    description: The log archive account for GovCloud.
    email: aws-logs-gc@nndata.com
    # this OU has all GovCloud accounts.
    # OU was created from Control Tower
    # in organization-config.yaml this OU was added.
    organizationalUnit: GovCloud
    # enableGovCloud is a one-time non-reversible option
    # which only works with creation of new accounts
    enableGovCloud: true
  - name: AuditGC # referred to as LogArchive in the GovCloud account-config.yaml
    description: The security audit account (also referred to as the audit account) for GovCloud.
    email: aws-audit-gc@nndata.com
    organizationalUnit: GovCloud
    enableGovCloud: true
  - name: SharedServicesGC # referred to as SharedServices in the GovCloud account-config.yaml
    description: Shared services (VDMS) account for GovCloud.
    email: aws-vdms-gc@nndata.com 
    organizationalUnit: GovCloud
    partition: aws-us-gov
    enableGovCloud: true
  - name: NetworkGC # referred to as Network in the GovCloud account-config.yaml
    description: Network account (VDSS) for GovCloud.
    email: aws-vdss-gc@nndata.com
    organizationalUnit: GovCloud
    enableGovCloud: true
  - name: Development
    description: Development Account in GovCloud.
    email: aws-dev-gc@nndata.com
    organizationalUnit: GovCloud
    enableGovCloud: true
  - name: QA
    description: QA Account in GovCloud.
    email: aws-qa-gc@nndata.com
    organizationalUnit: GovCloud
    enableGovCloud: true
  - name: Stage01
    description: Stage 01 Account in GovCloud.
    email: aws-stg01-gc@nndata.com 
    organizationalUnit: GovCloud
    partition: aws-us-gov
    enableGovCloud: true
  - name: Production 
    description: Production Workload Account in GovCloud.
    email: aws-prod-gc@nndata.com
    organizationalUnit: GovCloud
    enableGovCloud: true    