enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: GovCloud
  - name: BreakGlass
    ignore: true
    
ignoredOus:
  - BreakGlass

serviceControlPolicies: []
taggingPolicies: []
backupPolicies: []
